name: Release Edge Channel

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: snapcore/action-build@v1
      id: build
      with:
        snapcraft-args: --enable-experimental-package-repositories
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.EDGE_STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: edge
