#!/bin/bash -e

export LD_LIBRARY_PATH=$SNAP/lib/:$SNAP/usr/local/pgsql/lib/
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

# Create and chown the PostgreSQL data folder
DATA_DIR="$SNAP_DATA/pgsql/"
mkdir "$DATA_DIR"
chown -R snap_daemon:snap_daemon "$DATA_DIR"

# Initialize PostgreSQL database
$SNAP/usr/bin/setpriv --clear-groups --reuid snap_daemon --regid snap_daemon -- $SNAP/usr/local/pgsql/bin/initdb -U postgres -D $DATA_DIR
